## Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [1]:
import numpy as np
arr = np.arange(12,39)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

## Solution : np.pad(x,pad_width,mode,constant_value)


In [23]:
arr1 = np.ones([3,3])
print("original array:\n",arr1)
arr1 = np.pad(arr1, pad_width=1, mode='constant', constant_values=0)
print("0 on the border and 1 inside in the array\n",arr1)

original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [42]:
a_list = [1,2,3,4,5,6,7,8]
print("List:",a_list)
list_arr = np.array(a_list)
print("List to array:",list_arr)
a_tuple = tuple(a_list)
print("Tuple:",a_tuple)
tuple_arr = np.array(a_tuple)
print("Tuple to array:",tuple_arr)
tuple_sample = ((8,4,6),(1,2,3))
print("tuple:",tuple_sample)
print("type:",type(tuple_sample))
print("tuple to array:",np.array(tuple_sample))

List: [1, 2, 3, 4, 5, 6, 7, 8]
List to array: [1 2 3 4 5 6 7 8]
Tuple: (1, 2, 3, 4, 5, 6, 7, 8)
Tuple to array: [1 2 3 4 5 6 7 8]
tuple: ((8, 4, 6), (1, 2, 3))
type: <class 'tuple'>
tuple to array: [[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [64]:
far_value = [0,12,45.21,34,99.91]
far_value = np.array(far_value)
print("Values in Fahrenheit degrees:",far_value)
centi_value = (5*far_value/9 - 5*32/9)
print("Values in  Centigrade degrees:",centi_value)

Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [63]:
arr = np.array([1,2,3],dtype ='float')
print("Size of the array: ", arr.size)
print("Length of one array element in bytes: ", arr.itemsize)
print("Total bytes consumed by the elements of the array: ",arr.nbytes)





Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 6: Get the unique elements of an array

In [85]:
arr = [10, 10 ,20 ,20,30 ,30]
arr1 = np.array(arr)
print("Original array:",arr1)
arr2 = np.unique(arr1)
print("Unique elements of the above array:",arr2)


arr_another = np.array([[1,1],[2,3]])
print ("Original array:",arr_another)
arr_unique = np.unique(arr_another)
print("Unique elements of the above array:",arr_unique)

Original array: [10 10 20 20 30 30]
Unique elements of the above array: [10 20 30]
Original array: [[1 1]
 [2 3]]
Unique elements of the above array: [1 2 3]


## Exercise 7: Change the dimension of an array


In [96]:
harrae = np.array([1,2,3,4,5,6,7,8,9])
print("Original array: ",harrae)
harrae.shape=(3,3)
print("Change array shape to (3, 3) -> 3 rows and 3 columns\n",harrae)

Original array:  [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [106]:
space = np.linspace(2.5,6.5,30)
print("30 evenly spaced elements between 2.5. and 6.5\n\n",space)


30 evenly spaced elements between 2.5. and 6.5

 [2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [112]:
arra1 = np.array([10,20,30])
arra2 = np.array([40,50,60])
print("Array1: ",arra1)
print("Array2: ",arra2)
arra3 = np.column_stack((arra1,arra2))
print("Coverted array: \n",arra3)

Array1:  [10 20 30]
Array2:  [40 50 60]
Coverted array: 
 [[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [125]:
mat = np.zeros((5,5))
print("Original array: \n",mat)
mat1 = np.arange(5)+mat
print("Row values ranging from 0 to 4 \n",mat1)

Original array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [162]:
summ = np.arange(1,100)
print("Original numbers: \n\n",summ)
numm = summ[(summ % 3== 0) | (summ %5 == 0)]
print("\nThe Multiples of 3 or 5: \n\n",numm)
print("\nSum of only the multiples of 3  or 5 : \n\n",numm.sum())

Original numbers: 

 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]

The Multiples of 3 or 5: 

 [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]

Sum of only the multiples of 3  or 5 : 

 2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


## above is the example to execute below

In [173]:
ab1 = np.arange(4)
print("One dimensional array: ",ab1)
ab2 = np.arange(8).reshape(2,4)
print("Two dimensional array: \n",ab2)
for ab1,ab2 in np.nditer([ab1,ab2]):
    print("%d:%d" % (ab1,ab2))

One dimensional array:  [0 1 2 3]
Two dimensional array: 
 [[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [183]:
num_arr = np.array ([[0.42436315, 0.48558583, 0.32924763],[0.7439979,  0.58220701, 0.38213418],[0.5097581,  0.34528799, 0.1563123 ]])
print ("Original array: \n",num_arr)
num_arr[num_arr > 0.5 ] = 0.5
print("\nReplace all elements of the said array with .5 which are greater than .5\n",num_arr)

Original array: 
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]

Replace all elements of the said array with .5 which are greater than .5
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [205]:
arr = np.empty((0,3),int)
print("Empty array:",arr)
arr1 = np.append(arr,np.array([[10,20,30],[40,50,60]]),axis =0)
print("After adding two new arrays:\n",arr1)

Empty array: []
After adding two new arrays:
 [[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [237]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
print("Original arrays:\n",arr1)
print(arr2)
arr3 = np.vstack((arr1,arr2))
print("Sequence of arrays along a new axis:\n",arr3)

arr4 = np.array([[1],[2],[3]])
arr5 = np.array([[2],[3],[4]])
print("\n\nOriginal arrays:\n")
print(arr4)
print("\n",arr5)
arr6 = np.vstack((arr4,arr5))
print("\nSequence of arrays along a new axis:\n",arr6)

Original arrays:
 [1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
 [[1 2 3]
 [2 3 4]]


Original arrays:

[[1]
 [2]
 [3]]

 [[2]
 [3]
 [4]]

Sequence of arrays along a new axis:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


## Numpy Exercise Completed  